### ISSUE TITLE
Stdlib compat is being downgraded?

### ISSUE THREAD

**Issue by asinghvi17** [julia-actions/julia-downgrade-compat#12]
See these logs:

https://github.com/MakieOrg/GeoMakie.jl/actions/runs/11788769701/job/32836419174?pr=288

```
ERROR: LoadError: Unsatisfiable requirements detected for package Statistics [10745b16]:
 Statistics [10745b16] log:
 ├─possible versions are: 1.11.0 - 1.11.1 or uninstalled
 └─restricted to versions 1.0 by GeoMakie [db073c08] — no versions left
   └─GeoMakie [db073c08] log:
     ├─possible versions are: 0.7.8 or uninstalled
     └─GeoMakie [db073c08] is fixed to version 0.7.8
```

Should there be some form of exception for stdlibs?

**Comment by JoshuaLampert** [comment]
For stdlibs you should use `skip`, i.e.
```yml
      - uses: julia-actions/julia-downgrade-compat@v1
        with:
          skip: Statistics
```
